#
#    Copyright 2015-2022 the original author or authors.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       https://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#


logging:
  level:
    root: debug
    sample:
      mybatis:
          web:
            mapper: trace
mybatis:
  config-location: classpath:mybatis-config.xml

spring:
  datasource:
    url: jdbc:mysql://192.168.2.16:3306/study?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      minIdle: 6
      maxActive: 10
      pool-prepared-statements: true
      filters: stat
      maxWait: 6000
      max-open-prepared-statements: 20

